const fs = require('fs');
let code = fs.readFileSync('src/pages/country/spain/calculadora-de-calorias.astro', 'utf8');

code = code.replace(/ACA3mo/g, '¿Cómo')
           .replace(/calorA-as/g, 'calorías')
           .replace(/energA-a/g, 'energía')
           .replace(/metabA3lica/g, 'metabólica')
           .replace(/nAomero/g, 'número')
           .replace(/fA-sica/g, 'física')
           .replace(/energAcltica/g, 'energética')
           .replace(/fA3rmula/g, 'fórmula')
           .replace(/mAAAs/g, 'más')
           .replace(/pAclrdida/g, 'pérdida')
           .replace(/dAAcficit/g, 'déficit')
           .replace(/superAAvit/g, 'superávit')
           .replace(/calA3rico/g, 'calórico')
           .replace(/dAAca/g, 'día')
           .replace(/bAAAsicas/g, 'básicas')
           .replace(/respiraciA3n/g, 'respiración')
           .replace(/circulaciA3n/g, 'circulación')
           .replace(/sanguAA-nea/g, 'sanguínea')
           .replace(/funciA3n/g, 'función')
           .replace(/inglAAcs/g, 'inglés')
           .replace(/tAAclrmico/g, 'térmico')
           .replace(/digestiA3n/g, 'digestión')
           .replace(/CalorA-as/g, 'Calorías')
           .replace(/mAAAs/g, 'más')
           .replace(/cAAAlculo/g, 'cálculo')
           .replace(/genAAcltica/g, 'genética')
           .replace(/Acl/g, 'é')
           .replace(/AAAs/g, 'ás')
           .replace(/AA-a/g, 'ía')
           .replace(/A3/g, 'ó')
           .replace(/Acl/g, 'é')
           .replace(/Aon/g, 'ún')
           .replace(/Aon/g, 'ún')
           .replace(/AAcl/g, 'é')
           .replace(/AAcn/g, 'én')
           .replace(/AAoa/g, 'úa')
           .replace(/AA-n/g, 'ín');

// Actually, this manual regex might miss things. It's safer to overwrite the entire file using write_to_file but carefully!
