const fs = require('fs');

const englishCode = fs.readFileSync('src/components/calculators/CalorieCalculator.astro', 'utf8');

const translations = [
  ['CalorieCalculator', 'CalculadoraCalorias'],
  ['Los valores de ejemplo estAn prellenados', 'Los valores de ejemplo están prellenados'],
  ['MActrico', 'Métrico'],
  ['Edad', 'Edad'],
  ['Peso', 'Peso'],
  ['Altura', 'Altura'],
  ['Hombre', 'Hombre'],
  ['Mujer', 'Mujer'],
  ['Activity level', 'Nivel de actividad'],
  ['Sedentary — little or no exercise', 'Sedentario — poco o ningún ejercicio'],
  ['Lightly active — 1–3 days/week', 'Actividad ligera — ejercicio 1–3 días por semana'],
  ['Moderately active — 3–5 days/week', 'Actividad moderada — ejercicio 3–5 días por semana'],
  ['Very active — 6–7 days/week', 'Muy activo — ejercicio intenso 6–7 días/semana'],
  ['Extra active — hard exercise + job', 'Extremadamente activo — entreno intenso y/o trabajo físico'],
  ['Calculate', 'Calcular'],
  ['Adjust goal', 'Ajustar objetivo'],
  ['Maintain weight', 'Mantener mi peso'],
  ['Lose weight', 'Perder peso'],
  ['Gain weight', 'Ganar peso'],
  ['Daily calorie estimate', 'Calorías diarias recomendadas'],
  ['Base Metabolic Rate (BMR)', 'Tasa Metabólica Basal (TMB)'],
  ['calories/day', 'calorías/día'],
  ['Maintenance (TDEE)', 'Mantenimiento (GET/TDEE)'],
  ['Result summary', 'Resumen de resultados'],
  ['Macronutrient Guidelines', 'Guía de Macronutrientes'],
  ['Protein', 'Proteínas'],
  ['Carbs', 'Carbohidratos'],
  ['Fats', 'Grasas'],
  ['Example default values are pre-filled.', 'Los valores de ejemplo están prellenados.'],
  ['Enter your own details for an accurate result.', 'Ingresa tus propios datos para obtener un resultado preciso.'],
  ['Metric', 'Métrico'],
  ['Age', 'Edad'],
  ['Weight', 'Peso'],
  ['Height', 'Altura'],
  ['Sex', 'Sexo'],
  ['Male', 'Hombre'],
  ['Female', 'Mujer'],
  ['in centimetres', 'en centímetros'],
  ['in feet', 'en pies'],
  ['in inches', 'en pulgadas'],
  ['Moderate ratio:', 'Proporción moderada:'],
  ['High protein:', 'Alta proteína:'],
  ['Lower carb:', 'Bajo en carbohidratos:'],
  ['TDEE stands for', 'GET significa'],
  ['These macros are provided as a starting point. Adjust based on how your body responds.', 'Estos macros se proporcionan como punto de partida. Ajusta según cómo responda tu cuerpo.'],
  ['Daily Calorie Estimate', 'Calorías diarias recomendadas'],
  ['Weight <span', 'Peso <span'],
  ['Height <span', 'Altura <span'],
  ['aria-label="Height en centAmetros"', 'aria-label="Altura en centímetros"'],
  ['aria-label="Height en pies"', 'aria-label="Altura en pies"'],
  ['aria-label="Height en pulgadas"', 'aria-label="Altura en pulgadas"'],
  ['Your daily calories to <span id="goal-label"', 'Tus calorías diarias para <span id="goal-label"'],
  ['maintain weight', 'mantener peso'],
  ['Mild weight loss — 0.5 lb/week', 'Pérdida de peso leve — 0.25 kg/semana'],
  ['Weight loss — 1 lb/week', 'Pérdida de peso — 0.5 kg/semana'],
  ['Mild weight gain — 0.5 lb/week', 'Ganancia de peso leve — 0.25 kg/semana'],
  ['Weight gain — 1 lb/week', 'Ganancia de peso — 0.5 kg/semana'],
  ['Daily calories for each weight goal', 'Calorías diarias para cada objetivo'],
  ['Activity level', 'Nivel de actividad'],
  ['centAmetros', 'centímetros'],
  ['Maintain weight', 'Mantener peso'],
  ['Lose weight', 'Perder peso'],
  ['Gain weight', 'Ganar peso'],
  ['Result summary', 'Resumen de resultados'],
  ['Macronutrient Guidelines', 'Guía de Macronutrientes'],
  ['Protein', 'Proteínas'],
  ['Carbs', 'Carbohidratos'],
  ['Fats', 'Grasas'],
  ['Daily calorie estimate', 'Calorías diarias recomendadas'],
  ['Base Metabolic Rate (BMR)', 'Tasa Metabólica Basal (TMB)'],
  ['calories/day', 'calorías/día'],
  ['Maintenance (TDEE)', 'Mantenimiento (GET/TDEE)']
];

let code = englishCode;
for (const [en, es] of translations) {
  code = code.split(en).join(es);
}

fs.writeFileSync('src/components/calculators/CalculadoraCalorias.astro', code, 'utf8');
